### ISSUE TITLE
Einheiten der Energie überprüfen

### ISSUE THREAD

**Issue by JD46** [EnergizedTechLabsDo/energized#1]
Super Datensatz Saqib. Danke dir für deine Mühe :). Da ich nicht direkt die Zahlen im Master ändern wollte, sollten wir morgen noch einmal durchgehen, welche Einheiten genau vorkommen und diese, falls nötig, umrechnen. Ich bin mit denselben Daten auf andere Werte gekommen.

**Comment by MarinaMrd** [comment]
Danke an Saqib und JD!!
